import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nav_menu = ["home", "about", "posts", "contact"];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex width-full justify-between p-2">
          <Link href="/">
            <span className="text-xl font-semibold">Jenn's Blog</span>
          </Link>

          <nav>
            {nav_menu.map((menu) => (
              <Link
                className="p-2 text-sm"
                href={menu === "home" ? "/" : `/${menu}`}
              >
                {menu}
              </Link>
            ))}
          </nav>
        </header>
        {children}
        <footer className="text-slate-300 bg-slate-900 text-sm text-center p-2">
          <span>Don't forget to CODE your dream | Alright reserved</span>
        </footer>
      </body>
    </html>
  );
}
